# 1. Properties defined in the default application.properties or application.yml have a higher precedence than those loaded via @PropertySource
# 2. By default, @PropertySource does not support YAML files
server.port=${PORT:8081}