/*
 * This source file was generated by the Gradle 'init' task
 */
package hello;

import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.hasItem;

@RunWith(SpringRunner.class)
@WebMvcTest(ListController.class)
public class ListControllerTest {
    @Autowired
    private MockMvc mvc;

    @Test
    public void testEndpoint() throws Exception {

        mvc.perform(get("/list")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                // $ refer to root element
                .andExpect(jsonPath("$", hasSize(3)))
                // $[0] refer to first element of the list
                .andExpect(jsonPath("$[0]").value("Java"))
                .andExpect(jsonPath("$[1]").value("React"))
                .andExpect(jsonPath("$[2]").value("JavaScript"))

                // normally list order is not fix, better use hasItem
                // to test if it contains a specific value
                .andExpect(jsonPath("$", hasItem("React")));

    }
}
