/*
 * This source file was generated by the Gradle 'init' task
 */
package hello;

import java.util.Map;

import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import static org.junit.jupiter.api.Assertions.assertEquals;

@RunWith(SpringRunner.class)
@WebMvcTest(MapController.class)
public class MapControllerTest {
    @Autowired
    private MockMvc mvc;

    @Test
    public void testMap() throws Exception {
        mvc.perform(get("/map")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.key1").value("a"))
                .andExpect(jsonPath("$.key2").value("b"))
                .andExpect(jsonPath("$.key3").value("c"));

        // Deserialize and assert to test the map size, is there a better way?
        MvcResult result = mvc.perform(get("/map")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andReturn();

        // convert JSON to Map object
        String content = result.getResponse().getContentAsString();
        Map<String, Object> resultMap = new ObjectMapper().readValue(content, new TypeReference<>() {
        });

        assertEquals(3, resultMap.size());
    }
}
